<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="slt01-PC" ignored="0" name="Default test" tests="11" failures="2" timestamp="09 May 2019 09:24:39 GMT" time="0.115" errors="0">
  <testcase name="test1" time="0.008" classname="DataProvider01"/>
  <testcase name="test1" time="0.0" classname="DataProvider01"/>
  <testcase name="test1" time="0.0" classname="DataProvider01"/>
  <testcase name="test2" time="0.001" classname="DataProvider01"/>
  <testcase name="test2" time="0.001" classname="DataProvider01"/>
  <testcase name="test2" time="0.0" classname="DataProvider01"/>
  <testcase name="test3" time="0.001" classname="DataProvider01"/>
  <testcase name="test3" time="0.001" classname="DataProvider01"/>
  <testcase name="test3" time="0.001" classname="DataProvider01"/>
  <testcase name="test4" time="0.005" classname="DataProvider01">
    <failure type="java.lang.AssertionError" message="expected [111] but found [张三]">
        <![CDATA[java.lang.AssertionError: expected [111] but found [张三]
	at DataProvider01.test4(DataProvider01.java:68)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.005" classname="DataProvider01">
    <failure type="java.lang.AssertionError" message="expected [111] but found [李四]">
        <![CDATA[java.lang.AssertionError: expected [111] but found [李四]
	at DataProvider01.test4(DataProvider01.java:68)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
</testsuite> <!-- Default test -->
