<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="slt01-PC" ignored="0" name="测试2" tests="5" failures="1" timestamp="23 四月 2019 07:34:14 GMT" time="0.026" errors="0">
  <testcase name="testCase1" time="0.0" classname="com.hsl.cn.cn.TestQuery"/>
  <testcase name="testCase2" time="0.004" classname="com.hsl.cn.cn.TestQuery">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase2" time="0.001" classname="com.hsl.cn.cn.TestQuery">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase2" time="0.001" classname="com.hsl.cn.cn.TestQuery">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase2" time="0.0" classname="com.hsl.cn.cn.TestQuery">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
        <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.hsl.cn.cn.TestQuery.testCase2(TestQuery.java:23)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
</testsuite> <!-- 测试2 -->
